# Generated by Django 5.2 on 2025-05-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader_ytdlp', '0002_downloadlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlog',
            name='task_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
